### ISSUE TITLE
bug report: abacus evo stucked

### ISSUE THREAD

**Issue by ixsluo** [ICCMS-CALYPSO/CALYPSO-Bohrium#19]
1. structure evolution may stuck in abacus
2. pickup of abacus should be improved, CONTCAR/POSCAR of each step should be saved

@wangzyphysics

**Comment by wangzyphysics** [comment]
1. the stuck are arised by the low percision of ABACUS input which is not the calypso's problem
2. POSCAR now has been saved into the data/ directory for pickup
@ixsluo
